version: "3.9"
services:
  frontend-dev:
    image: node:17-alpine
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/root" # Has to be in root because of https://github.com/vitejs/vite/issues/6767
    working_dir: "/root"
    entrypoint: ["npm", "run", "dev"]
  backend-dev:
    build: ./backend
    volumes:
      - "./backend:/home/node/app:ro"
      - "./recorded_files:/home/node/audio:rw"
      - "./audio_clips:/home/node/clips:ro"
    entrypoint: "npm run dev"
    expose:
      - "3000"
  nginx-dev:
    image: nginx:1.21-alpine
    volumes:
      - "./nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"
    depends_on:
      - frontend-dev
      - backend-dev
